//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karpach.Wemo.Switcher.WemoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="WemoService.BasicServicePortType")]
    public interface BasicServicePortType {
        
        // CODEGEN: Generating message contract since the operation SetBinaryState is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1 SetBinaryState(Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1> SetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetBinaryState is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1 GetBinaryState(Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1> GetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetFriendlyName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1 GetFriendlyName(Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1> GetFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHomeId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1 GetHomeId(Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1> GetHomeIdAsync(Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest request);
        
        // CODEGEN: Generating message contract since the operation GetSignalStrength is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1 GetSignalStrength(Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1> GetSignalStrengthAsync(Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest request);
        
        // CODEGEN: Generating message contract since the operation GetLogFileURL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1 GetLogFileURL(Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1> GetLogFileURLAsync(Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest request);
        
        // CODEGEN: Generating message contract since the operation GetIconURL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1 GetIconURL(Karpach.Wemo.Switcher.WemoService.GetIconURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1> GetIconURLAsync(Karpach.Wemo.Switcher.WemoService.GetIconURLRequest request);
        
        // CODEGEN: Generating message contract since the operation ChangeFriendlyName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1 ChangeFriendlyName(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.SetBinaryState SetBinaryState;
        
        public SetBinaryStateRequest() {
        }
        
        public SetBinaryStateRequest(Karpach.Wemo.Switcher.WemoService.SetBinaryState SetBinaryState) {
            this.SetBinaryState = SetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse SetBinaryStateResponse;
        
        public SetBinaryStateResponse1() {
        }
        
        public SetBinaryStateResponse1(Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse SetBinaryStateResponse) {
            this.SetBinaryStateResponse = SetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetBinaryState GetBinaryState;
        
        public GetBinaryStateRequest() {
        }
        
        public GetBinaryStateRequest(Karpach.Wemo.Switcher.WemoService.GetBinaryState GetBinaryState) {
            this.GetBinaryState = GetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse GetBinaryStateResponse;
        
        public GetBinaryStateResponse1() {
        }
        
        public GetBinaryStateResponse1(Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse GetBinaryStateResponse) {
            this.GetBinaryStateResponse = GetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetFriendlyName GetFriendlyName;
        
        public GetFriendlyNameRequest() {
        }
        
        public GetFriendlyNameRequest(Karpach.Wemo.Switcher.WemoService.GetFriendlyName GetFriendlyName) {
            this.GetFriendlyName = GetFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse GetFriendlyNameResponse;
        
        public GetFriendlyNameResponse1() {
        }
        
        public GetFriendlyNameResponse1(Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse GetFriendlyNameResponse) {
            this.GetFriendlyNameResponse = GetFriendlyNameResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeId : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string homeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
                this.RaisePropertyChanged("HomeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetHomeId GetHomeId;
        
        public GetHomeIdRequest() {
        }
        
        public GetHomeIdRequest(Karpach.Wemo.Switcher.WemoService.GetHomeId GetHomeId) {
            this.GetHomeId = GetHomeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse GetHomeIdResponse;
        
        public GetHomeIdResponse1() {
        }
        
        public GetHomeIdResponse1(Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse GetHomeIdResponse) {
            this.GetHomeIdResponse = GetHomeIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrength : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrengthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signalStrengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignalStrength {
            get {
                return this.signalStrengthField;
            }
            set {
                this.signalStrengthField = value;
                this.RaisePropertyChanged("SignalStrength");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetSignalStrength GetSignalStrength;
        
        public GetSignalStrengthRequest() {
        }
        
        public GetSignalStrengthRequest(Karpach.Wemo.Switcher.WemoService.GetSignalStrength GetSignalStrength) {
            this.GetSignalStrength = GetSignalStrength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse GetSignalStrengthResponse;
        
        public GetSignalStrengthResponse1() {
        }
        
        public GetSignalStrengthResponse1(Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse GetSignalStrengthResponse) {
            this.GetSignalStrengthResponse = GetSignalStrengthResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lOGURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGURL {
            get {
                return this.lOGURLField;
            }
            set {
                this.lOGURLField = value;
                this.RaisePropertyChanged("LOGURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetLogFileURL GetLogFileURL;
        
        public GetLogFileURLRequest() {
        }
        
        public GetLogFileURLRequest(Karpach.Wemo.Switcher.WemoService.GetLogFileURL GetLogFileURL) {
            this.GetLogFileURL = GetLogFileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse GetLogFileURLResponse;
        
        public GetLogFileURLResponse1() {
        }
        
        public GetLogFileURLResponse1(Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse GetLogFileURLResponse) {
            this.GetLogFileURLResponse = GetLogFileURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetIconURL GetIconURL;
        
        public GetIconURLRequest() {
        }
        
        public GetIconURLRequest(Karpach.Wemo.Switcher.WemoService.GetIconURL GetIconURL) {
            this.GetIconURL = GetIconURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.GetIconURLResponse GetIconURLResponse;
        
        public GetIconURLResponse1() {
        }
        
        public GetIconURLResponse1(Karpach.Wemo.Switcher.WemoService.GetIconURLResponse GetIconURLResponse) {
            this.GetIconURLResponse = GetIconURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.ChangeFriendlyName ChangeFriendlyName;
        
        public ChangeFriendlyNameRequest() {
        }
        
        public ChangeFriendlyNameRequest(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyName ChangeFriendlyName) {
            this.ChangeFriendlyName = ChangeFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse ChangeFriendlyNameResponse;
        
        public ChangeFriendlyNameResponse1() {
        }
        
        public ChangeFriendlyNameResponse1(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse ChangeFriendlyNameResponse) {
            this.ChangeFriendlyNameResponse = ChangeFriendlyNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicServicePortTypeChannel : Karpach.Wemo.Switcher.WemoService.BasicServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicServicePortTypeClient : System.ServiceModel.ClientBase<Karpach.Wemo.Switcher.WemoService.BasicServicePortType>, Karpach.Wemo.Switcher.WemoService.BasicServicePortType {
        
        public BasicServicePortTypeClient() {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.SetBinaryState(Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryState(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse SetBinaryState(Karpach.Wemo.Switcher.WemoService.SetBinaryState SetBinaryState1) {
            Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest inValue = new Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState1;
            Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).SetBinaryState(inValue);
            return retVal.SetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.SetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.SetBinaryStateResponse1> SetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.SetBinaryState SetBinaryState) {
            Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest inValue = new Karpach.Wemo.Switcher.WemoService.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).SetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetBinaryState(Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryState(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse GetBinaryState(Karpach.Wemo.Switcher.WemoService.GetBinaryState GetBinaryState1) {
            Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState1;
            Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetBinaryState(inValue);
            return retVal.GetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetBinaryStateResponse1> GetBinaryStateAsync(Karpach.Wemo.Switcher.WemoService.GetBinaryState GetBinaryState) {
            Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetFriendlyName(Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyName(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse GetFriendlyName(Karpach.Wemo.Switcher.WemoService.GetFriendlyName GetFriendlyName1) {
            Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName1;
            Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetFriendlyName(inValue);
            return retVal.GetFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetFriendlyNameResponse1> GetFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.GetFriendlyName GetFriendlyName) {
            Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetFriendlyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetHomeId(Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest request) {
            return base.Channel.GetHomeId(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse GetHomeId(Karpach.Wemo.Switcher.WemoService.GetHomeId GetHomeId1) {
            Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId1;
            Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetHomeId(inValue);
            return retVal.GetHomeIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetHomeIdAsync(Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest request) {
            return base.Channel.GetHomeIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetHomeIdResponse1> GetHomeIdAsync(Karpach.Wemo.Switcher.WemoService.GetHomeId GetHomeId) {
            Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetHomeIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetSignalStrength(Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrength(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse GetSignalStrength(Karpach.Wemo.Switcher.WemoService.GetSignalStrength GetSignalStrength1) {
            Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength1;
            Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetSignalStrength(inValue);
            return retVal.GetSignalStrengthResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetSignalStrengthAsync(Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrengthAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetSignalStrengthResponse1> GetSignalStrengthAsync(Karpach.Wemo.Switcher.WemoService.GetSignalStrength GetSignalStrength) {
            Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetSignalStrengthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetLogFileURL(Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURL(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse GetLogFileURL(Karpach.Wemo.Switcher.WemoService.GetLogFileURL GetLogFileURL1) {
            Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL1;
            Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetLogFileURL(inValue);
            return retVal.GetLogFileURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetLogFileURLAsync(Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetLogFileURLResponse1> GetLogFileURLAsync(Karpach.Wemo.Switcher.WemoService.GetLogFileURL GetLogFileURL) {
            Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetLogFileURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetIconURL(Karpach.Wemo.Switcher.WemoService.GetIconURLRequest request) {
            return base.Channel.GetIconURL(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.GetIconURLResponse GetIconURL(Karpach.Wemo.Switcher.WemoService.GetIconURL GetIconURL1) {
            Karpach.Wemo.Switcher.WemoService.GetIconURLRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL1;
            Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetIconURL(inValue);
            return retVal.GetIconURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.GetIconURLAsync(Karpach.Wemo.Switcher.WemoService.GetIconURLRequest request) {
            return base.Channel.GetIconURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.GetIconURLResponse1> GetIconURLAsync(Karpach.Wemo.Switcher.WemoService.GetIconURL GetIconURL) {
            Karpach.Wemo.Switcher.WemoService.GetIconURLRequest inValue = new Karpach.Wemo.Switcher.WemoService.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).GetIconURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1 Karpach.Wemo.Switcher.WemoService.BasicServicePortType.ChangeFriendlyName(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyName(request);
        }
        
        public Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse ChangeFriendlyName(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyName ChangeFriendlyName1) {
            Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest inValue = new Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName1;
            Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1 retVal = ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).ChangeFriendlyName(inValue);
            return retVal.ChangeFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1> Karpach.Wemo.Switcher.WemoService.BasicServicePortType.ChangeFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(Karpach.Wemo.Switcher.WemoService.ChangeFriendlyName ChangeFriendlyName) {
            Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest inValue = new Karpach.Wemo.Switcher.WemoService.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName;
            return ((Karpach.Wemo.Switcher.WemoService.BasicServicePortType)(this)).ChangeFriendlyNameAsync(inValue);
        }
    }
}
